Fix compilation error on macOS
Latest clang with -developer-build stops with

error: cast from 'NativeResourceForIntegrationFunction' (aka 'void *(*)()') to 'EnableTouch' (aka 'void *(*)(QWindow *, bool)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch

Adapt the fix already applied to e.g. qtgraphs (QTBUG-136654) here, too.

Pick-to: 6.9.1
Change-Id: I479cad4cdabfba67d83bdb6a48ebe89ec3fd5555
Reviewed-by: Tomi Korpipää <tomi.korpipaa@qt.io>
(cherry picked from commit fa91bd95fe13ba858050be7d1a536563c2bc91f2)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>